<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
کثیر السفر
</font>
</h1>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>

</font>
</p>

In [1]:
import numpy as np
import numpy.linalg as la

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
بخش اول
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
به ازای ۳ مقدار احتمال اولیه داده شده در هر سل، احتمال حضور الیزابت در هر شهر در روز ۷ ام را محاسبه کنید و به ترتیب در متغیر‌های b ،a و c (به صورت آرایه نامپای) ذخیره نمایید.
</font>
</p>

In [2]:
T1 = np.array([[0  , 1/4, 0 , 0 , 0  , 1/5],
               [1/3,  0 , 0 ,1/2,1/2 ,  0 ],
               [0  , 1/4, 0 , 0 , 0  , 1/5],
               [0  , 1/4, 1 ,1/2,1/2 , 1/5],
               [1/3, 1/4, 0 , 0 , 0  , 1/5],
               [1/3,  0 , 0 , 0 , 0  , 1/5]])

In [3]:
p = np.array([0,0,0,0,0,100])

In [4]:
a = np.dot(la.matrix_power(T1, 7), p)

In [5]:
p = np.array([0,0,0,50,0,50])

In [6]:
b = np.dot(la.matrix_power(T1, 7), p)

In [7]:
p = np.array([50,10,10,10,10,10])

In [8]:
c = np.dot(la.matrix_power(T1, 7), p)


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
مقادیر ويژه ماتریس <code>T1</code> را محاسبه کرده و آن‌ها را به ترتیب از مقدار ویژه با اندازه بزرگتر تا مقدار ویژه با کوچکترین اندازه درون آرایه <code>eig1</code> قرار دهید.
</font>
</p>

In [11]:
#eig1 = np.abs(sorted(la.eigvals(T1), key=lambda x: np.abs(x), reverse=True))
#eig1 = sorted(np.abs((la.eigvals(T1))), reverse=True)
#eig1 = sorted(la.eigvals(T1), reverse=True)
#eig1 = np.abs(la.eigvals(T1))
#eig1 = np.sort(la.eigvals(T1))[::-1]
#eig1
#eig1 = np.abs(eig1)
#eig1
#eig1 = np.sort(eig1)[::-1]
#eig1
#np.abs(sorted((la.eigvals(T1)), reverse=True))
#print(eig1)
eigvals, eigvecs = np.linalg.eig(T1)
idx = np.absolute(eigvals).argsort()
idx = idx[::-1]
eigvals = eigvals[idx]
#eigvecs = eigvecs[:,idx]
eig1 = eigvals
eig1

array([ 1.00000000e+00+0.00000000e+00j, -2.59696331e-01-2.15658885e-01j,
       -2.59696331e-01+2.15658885e-01j,  2.19392663e-01+0.00000000e+00j,
        9.55482811e-17-6.84501121e-09j,  9.55482811e-17+6.84501121e-09j])


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
بوکر نیز همانند الیزابت در جزیره 
2K
هر روز یک سفر انجام می‌دهد. اما یا این تفاوت که برخلاف الیزابت از مسیر‌های زیرزمینی جزیره استفاده می‌کند. در ادامه ماتریس سفر مسیر‌های زیرزمینی با توجه با نام <code>T2</code> 
آورده شده است. 
</font>
</p>

In [12]:
T2 = np.array([[0   ,  1/4  ,  1/3 ,  1/3 ,  0  ,   0],
              [1/3  ,  1/4  ,   0  ,  1/3 ,  0  ,   0],
              [1/3  ,  1/4  ,  1/3 ,   0  ,  0  ,   0],
              [1/3  ,  1/4  ,  1/3 ,  1/3 ,  0  ,   0],
              [0    ,   0   ,   0  ,   0  ,  1  ,   0],
              [0    ,   0   ,   0  ,   0  ,  0  ,   1 ]])


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
به ازای ۲ مقدار احتمال اولیه داده شده در هر سل، احتمال حضور بوکر در هر شهر در روز ۷ ام را محاسبه کنید و به ترتیب در متغیر‌های d و f  ذخیره نمایید.
</font>
</p>

In [13]:
p = np.array([10,20,0,0,30,40])

In [14]:
d = np.dot(la.matrix_power(T2, 7), p)

In [15]:
p = np.array([50,10,10,10,10,10])

In [16]:
e = np.dot(la.matrix_power(T2, 7), p)


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
مقادیر ويژه ماتریس <code>T2</code> را محاسبه کرده و آن‌ها را به ترتیب از مقدار ویژه با اندازه بزرگتر تا مقدار ویژه با کوچکترین اندازه درون آرایه <code>eig2</code> قرار دهید.
</font>
</p>

In [17]:
#eig2 = sorted((la.eigvals(T2)), reverse=True)
#eig2 = np.abs(sorted(la.eigvals(T2), reverse=True))
#print(eig2)
eigvals, eigvecs = np.linalg.eig(T2)
idx = np.absolute(eigvals).argsort()
idx = idx[::-1]
eigvals = eigvals[idx]
#eigvecs = eigvecs[:,idx]
eig2 = eigvals
eig2

array([ 1.        +0.j        ,  1.        +0.j        ,
        1.        +0.j        , -0.28962562+0.j        ,
        0.10314614-0.14605008j,  0.10314614+0.14605008j])

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
بخش دوم
<font face="vazir" color="#0099cc">
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>اکنون با تحلیل نتایج بخش‌های قبل، تابعی بنویسید که یک ماتریس سفر را به عنوان ورودی دریافت کند و بردار ویژه متناظر مقدار ویژه برابر ۱ ماتریس را بدون استفاده از   ماژول <code>linalg</code> نامپای محاسبه کند. این تضمین وجود دارد که ورودی دقیقا یک مقدار ويژه برابر ۱ دارد و جمع درایه‌های بردار ویژه خروجی مخالف صفر است. بردار ویژه خروجی باید به نحوی باشد که جمع درایه‌های آن برابر ۱۰۰ گردد.</font>
</p>

In [18]:
def eigvector_1 (T):
    import numpy as np
    n = len(T)
    v = np.ones(n) / n  # Start with a random vector
    while True:
        v_next = np.dot(T, v)
        v_next /= np.sum(v_next) / 100  # Normalize to make the sum equal to 100
        if np.allclose(v, v_next):
            break
        v = v_next
    return v
print(eigvector_1(T1))
print(eigvector_1(T2))

[ 7.84316685 28.75808943  7.84316685 41.83004303 10.45756023  3.26797362]
[15.65226383 16.23182835 13.91302143 20.86955305 16.66666667 16.66666667]


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
با استفاده از دستور جادویی <code>save</code> کد تابع خود را در قالب فایل <code dir=ltr>.py</code> ذخیره کنید تا بتوانیم در سلول جواب‌ساز، آن را در فایل <code>result.zip</code> قرار دهیم.
</font>
</p>


In [19]:
from inspect import getsource
%save eigvector_1 getsource(eigvector_1)

The following commands were written to file `eigvector_1.py`:
def eigvector_1 (T):
    import numpy as np
    n = len(T)
    v = np.ones(n) / n  # Start with a random vector
    while True:
        v_next = np.dot(T, v)
        v_next /= np.sum(v_next) / 100  # Normalize to make the sum equal to 100
        if np.allclose(v, v_next):
            break
        v = v_next
    return v



<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [20]:
import zlib
import zipfile
import joblib

joblib.dump(a,"a")
joblib.dump(b,"b")
joblib.dump(c,"c")
joblib.dump(d,"d")
joblib.dump(e,"e")

joblib.dump(eig1,"eig1")
joblib.dump(eig2,"eig2")

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

file_names = ['a','b','c','d','e','eig1','eig2','eigvector_1.py' , 'frequent_traveler.ipynb']

compress(file_names)

File Paths:
['a', 'b', 'c', 'd', 'e', 'eig1', 'eig2', 'eigvector_1.py', 'frequent_traveler.ipynb']
