<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
دست‌گرمی
</font>
</h1>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در این تمرین می‌خواهیم مقدمات کار با <code>numpy</code> را با هم تمرین کنیم.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
سوال ۱
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در سوال ۱ قصد داریم نسبت به سرعت بالای آرایه‌های 
<code>numpy</code>
 در مقایسه با لیست‌های پایتون در محاسبات عددی شهود بهتری پیدا کنیم.
 بدین منظور از شما می‌خواهیم به دو روش تابع محاسبه نرم اقلیدسی (نرم ۲) را بنویسید. این تابع  لیستی از اعداد را (که نمایانگر یک بردار است) به عنوان ورودی گرفته و نرم 
 اقلیدسی آن را به خروجی می‌دهد. فرمول محاسبه نرم اقلیدسی بردار
 <code>X</code>
در ادامه آمده است.
</font>
</p>

$$
\|\mathbf{X}\|_2 = \sqrt{\sum_{i=1}^n x_i^2}
$$


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
<b style="color:#0099cc">توضیح فرمول:</b>
نخست هر عنصر لیست را به توان ۲ رسانده، سپس این مقادیر را با همدیگر جمع کرده و نهایتاً از آن‌ جذر بگیرید.
</p>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
 در حالت اول تابعی تحت عنوان <code>euclidean_norm_list</code> بنویسید. این تابع را بدون استفاده از پکیج </font>
<code>numpy</code>
و تنها با توابع و متد‌های لیست پایتون پیاده‌سازی کنید. می‌توانید در صورت نیاز از ماژول <code>math</code>
استفاده کنید.
</p>

In [21]:
def euclidean_norm_list(mylist):
    import math
    squared_sum = 0
    for num in mylist:
        squared_sum += num**2
    result = math.sqrt(squared_sum)
    return result


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
اکنون تابعی با نام 
<code>euclidean_norm_np</code>
بنویسید تا نرم اقلیدسی را با استفاده از پکیج <code>numpy</code>
محاسبه کند.
</p>

In [22]:
def euclidean_norm_np(mylist):
    import numpy as np
    norm = np.linalg.norm(mylist)
    return norm


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
جهت مقایسه سرعت اجرای دو تابع، از دستور جادویی 
<code>timeit</code>    
 و برای ذخیره نتایج در متغیر‌های <code>a</code> و <code>b</code> از آرگومان 
<code dir=ltr>-o</code>
استفاده خواهیم کرد. 
جهت کسب اطلاعات بیشتر درباره‌ی <i>دستورات جادویی (magic codes)</i> می‌توانید به این
<a href="https://coderzcolumn.com/tutorials/python/list-of-useful-magic-commands-in-jupyter-notebook-lab"> لینک</a>
مراجعه کنید.
لیست اعداد ورودی برای تست توابع و دستورات
<code>timeit</code> 
در ادامه آمده است، تنها لازم است پس از تکمیل توابع فوق قطعه کد‌های زیر را اجرا نمایید تا مدت زمان اجرای هر تابع را در خروجی دریافت کنید. 
</p>

In [23]:
input = list(range(1000000))

In [24]:
a = %timeit -o euclidean_norm_list(input)

1.09 s ± 343 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [25]:
b = %timeit -o euclidean_norm_np(input)

197 ms ± 8.71 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
با استفاده از دستور جادویی <code>save</code> کد تابع خود را در قالب فایل <code dir=ltr>.py</code> ذخیره کنید تا بتوانیم در سلول جواب‌ساز، آن را در فایل <code>result.zip</code> قرار دهیم.
</font>
</p>


In [26]:
from inspect import getsource
%save euclidean_norm_list getsource(euclidean_norm_list)
%save euclidean_norm_np getsource(euclidean_norm_np)

The following commands were written to file `euclidean_norm_list.py`:
def euclidean_norm_list(mylist):
    import math
    squared_sum = 0
    for num in mylist:
        squared_sum += num**2
    result = math.sqrt(squared_sum)
    return result

The following commands were written to file `euclidean_norm_np.py`:
def euclidean_norm_np(mylist):
    import numpy as np
    norm = np.linalg.norm(mylist)
    return norm



<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
سوال ۲
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در این بخش از شما می‌خواهیم تابعی به نام <code>custom_filter</code>
 با دو ورودی 
<code>arr</code>
و
<code>L</code>
بنویسید که
<code>arr</code>
یک آرایه‌ی دو بعدی متشکل از آرایه‌های تک بعدی با طول 
<code>n</code>
است و 
<code>L</code>
لیستی به طول 
<code>n</code> باشد.
عملکرد تابع 
<code>custom_filter</code>
به این‌صورت است که نخست <code>L</code> را به انتهای آرایه <code>arr</code> اضافه‌ می‌کند (منظور <code>append</code> است)، سپس در آرایه‌ی دو بعدی جدید، هر ستونی (آرایه‌ی دوبعدی را همچون یک ماتریس در نظر بگیرید) را که شامل عددی بزرگتر مساوی ۱۰ یا کوچکتر مساوی ۱ است از آرایه حذف می‌کند و نهایتاً آرایه را به خروجی تابع می‌دهد. چنان‌چه آرایه‌ی خروجی تهی باشد به جای آن عبارت <code>Null</code> به صورت <code>string</code> در خروجی نمایش داده می‌شود. 
</font>
</p>

In [27]:
def custom_filter(arr,L):
    import numpy as np
    # convert to numpy arrays
    arr = np.array(arr)
    L = np.array(L)

    # append L to arr
    arr = np.vstack((arr, L))

    # filter the columns in the 2-d array
    filtered_columns = [col for col in arr.T if ((col >= 10) | (col <=1)).sum() == 0]

    # check if filtered_columns is empty
    if len(filtered_columns) == 0:
        return "Null"
    else:
        return np.array(filtered_columns).T


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
<b style="color:purple">توجه:</b>
نمونه‌هایی از ورودی و خروجی تابع به صورت کامنت در سلول زیر قرار داده شده است. 
</font>
</p>

In [28]:
###################################################################################
#Ex1: 
print(custom_filter(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),[8,9,10]))
# array([[2],
#        [5],
#        [8],
#        [9]])
#
#Ex2: 
print(custom_filter(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),[7,8,9]))
# array([[2, 3],
#        [5, 6],
#        [8, 9],
#        [8, 9]])
#
#Ex3: 
print(custom_filter(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),[9,10,11]))
# 'Null'
###################################################################################

[[2]
 [5]
 [8]
 [9]]
[[2 3]
 [5 6]
 [8 9]
 [8 9]]
Null


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
با استفاده از دستور جادویی <code>save</code> کد تابع خود را در قالب فایل <code dir=ltr>.py</code> ذخیره کنید تا بتوانیم در سلول جواب‌ساز، آن را در فایل <code>result.zip</code> قرار دهیم.
</font>
</p>


In [29]:
from inspect import getsource
%save custom_filter getsource(custom_filter)

The following commands were written to file `custom_filter.py`:
def custom_filter(arr,L):
    import numpy as np
    # convert to numpy arrays
    arr = np.array(arr)
    L = np.array(L)

    # append L to arr
    arr = np.vstack((arr, L))

    # filter the columns in the 2-d array
    filtered_columns = [col for col in arr.T if ((col >= 10) | (col <=1)).sum() == 0]

    # check if filtered_columns is empty
    if len(filtered_columns) == 0:
        return "Null"
    else:
        return np.array(filtered_columns).T



<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [30]:
import zlib
import zipfile
import joblib

joblib.dump(a,"a")
joblib.dump(b,"b")

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

file_names = ['euclidean_norm_list.py', 'euclidean_norm_np.py',
              'custom_filter.py', 'a', 'b', 'warm_up.ipynb']

compress(file_names)

File Paths:
['euclidean_norm_list.py', 'euclidean_norm_np.py', 'custom_filter.py', 'a', 'b', 'warm_up.ipynb']
